### ISSUE TITLE
`Index dirty` segfaults

### ISSUE THREAD

**Issue by OmarElawady** [rivine/0-db#123]
Happens with the static binary. Should this be `(dirty.length + 1) * 10` to handle empty index dirty list?
 https://github.com/threefoldtech/0-db/blob/development-v2/zdbd/commands_system.c#L212

**Comment by maxux** [comment]
Will investigate tomorrow.
What's the IDs you should have ? You know ?

**Comment by OmarElawady** [comment]
Executed this on a new zdb on the default namespace, so I expect no dirty indexes.
```bash
zdb --port 8888
redis-cli -p 8888 index dirty # in another session
```

**Comment by OmarElawady** [comment]
This is the backtrace with gdb on the static binary:
```gdb
#0  get_nominal_size (end=0x7ffff7ff86bc "", p=0x7ffff7ff86b0 "*0\r\n") at src/malloc/mallocng/meta.h:169
#1  __libc_free (p=0x7ffff7ff86b0) at src/malloc/mallocng/free.c:110
#2  0x0000000000406b1f in redis_response_free (response=0x7ffff7ff8550) at redis.c:138
#3  redis_reply_heap (client=client@entry=0x7ffff7ff8920, payload=payload@entry=0x7ffff7ff86b0, length=length@entry=4, destructor=0x4128ba <free>) at redis.c:260
#4  0x000000000040663a in command_index_dirty (client=0x7ffff7ff8920) at commands_system.c:224
#5  command_index (client=0x7ffff7ff8920) at commands_system.c:246
#6  0x0000000000407950 in redis_handle_resp_finished (client=0x7ffff7ff8920) at redis.c:656
#7  redis_chunk_read (fd=<optimized out>) at redis.c:780
#8  0x0000000000408a98 in socket_event (redis=<optimized out>, notified=<optimized out>, events=<optimized out>) at socket_epoll.c:88
#9  socket_handler (handler=handler@entry=0x7fffffffebc0) at socket_epoll.c:155
#10 0x00000000004083df in redis_listen (listenaddr=<optimized out>, port=<optimized out>, socket=<optimized out>) at redis.c:1361
#11 0x000000000040177c in proceed (zdbd_settings=0x42a520 <zdbd_rootsettings>, zdb_settings=0x42a5c0 <zdb_rootsettings>) at zdbd.c:251
#12 main (argc=6, argv=0x7fffffffed58) at zdbd.c:503

```

**Comment by maxux** [comment]
Confirmed with valgrind, fixed
