### ISSUE TITLE
zdb segfaults on scan command

### ISSUE THREAD

**Issue by OmarElawady** [rivine/0-db#130]
stacktrace from gdb, static binary v2.0.2:
```
(gdb) bt
#0  index_grab_fileid (root=root@entry=0x0, fileid=fileid@entry=0) at index.c:254
#1  0x000000000040ea22 in index_first_header (root=0x0) at index_scan.c:394
#2  0x0000000000404c3a in command_scan (client=0x7fffeffca990) at commands_scan.c:234
#3  0x0000000000407a20 in redis_handle_resp_finished (client=0x7fffeffca990) at redis.c:656
#4  redis_chunk_read (fd=<optimised out>) at redis.c:780
#5  0x0000000000408b68 in socket_event (redis=<optimised out>, notified=<optimised out>, events=<optimised out>) at socket_epoll.c:88
#6  socket_handler (handler=handler@entry=0x7fffffffdc60) at socket_epoll.c:155
#7  0x00000000004084af in redis_listen (listenaddr=<optimised out>, port=<optimised out>, socket=<optimised out>) at redis.c:1361
#8  0x00000000004017d3 in proceed (zdbd_settings=0x42c520 <zdbd_rootsettings>, zdb_settings=0x42c5c0 <zdb_rootsettings>) at zdbd.c:251
#9  main (argc=3, argv=0x7fffffffde08) at zdbd.c:515
```

Not sure exactly how to reproduce, but happened twice in the following flow:
- create namespaces -> fire up qsfs -> delete namespaces
- `redis-cli -p 9900` and then `select meta-1` # scan regularly

IIRC it only happens when meta-1 is deleted

**Comment by maxux** [comment]
Found how to reproduce. Fixing :)
